services:
  login-consent:
    build:
      context: ./login-consent-app
    environment:
      HYDRA_ADMIN_URL: http://hydra:4445
      DEMO_SUBJECT: user-001
      ADDR: :3000
    ports:
      - "3000:3000"
    depends_on:
      hydra:
        condition: service_started
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    command: ["migrate", "sql", "-e", "--yes"]
    restart: "no"

  hydra:
    image: oryd/hydra:v2.2.0
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
    ports:
      - "4444:4444"
      - "4445:4445"
    environment:
      DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      SECRETS_SYSTEM: ${HYDRA_SYSTEM_SECRET}

      URLS_SELF_ISSUER: ${HYDRA_ISSUER_URL}
      URLS_LOGIN: ${HYDRA_LOGIN_URL}
      URLS_CONSENT: ${HYDRA_CONSENT_URL}
      URLS_LOGOUT: ${HYDRA_LOGOUT_URL}

      OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: pairwise,public
      OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: ${HYDRA_PAIRWISE_SALT}

      LOG_LEVEL: debug
    command: ["serve", "all", "--dev"]

  go-app:
    build:
      context: ./go-app
    environment:
      ADDR: :8080
      BASE_URL: http://localhost:8080
      HYDRA_PUBLIC_INTERNAL_URL: http://hydra:4444
      HYDRA_PUBLIC_BROWSER_URL: http://localhost:4444
      OIDC_CLIENT_ID: demo-client
      OIDC_CLIENT_SECRET: demo-secret
      OIDC_REDIRECT_URI: http://localhost:8080/api/callback
      OIDC_JWKS_URL: http://hydra:4444/.well-known/jwks.json
      OIDC_ISSUER: http://localhost:4444/
      OIDC_EXPECTED_AUD: demo-client
      SESSION_SECRET: please-change-this-32chars-min
      VUE_APP_URL: http://localhost:5173/app
    ports:
      - "8080:8080"
    depends_on:
      hydra:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      go-app:
        condition: service_started
volumes:
  frontend_node_modules:
